import { Metadata, Viewport } from "next"
import MainLayout from "./components/MainLayout"

export const metadata:Metadata= {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export const viewport: Viewport = {
  width: "device-width",
  height: "device-height",
  initialScale: 1,
  maximumScale: 1,
  minimumScale: 1,
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body>
        <MainLayout>
        {children}
        </MainLayout>
       
        </body>
    </html>
  )
}
